CREATE TABLE IF NOT EXISTS shaders (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  manifest JSONB NOT NULL,
  code TEXT NOT NULL,
  meta JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS presets (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  name TEXT,
  shader_id INTEGER NOT NULL REFERENCES shaders(id) ON DELETE CASCADE,
  params JSONB NOT NULL
);

CREATE INDEX IF NOT EXISTS presets_shader_id_idx ON presets (shader_id);
